apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pacman
spec:
  workspaces:
  - name: shared-workspace
  resources:
  - name: source-repo
    type: git
  - name: image
    type: image
  params:
  - name: kustomization-path
    type: string
    default: kustomization
  - name: kustomization-git-repo-url
    type: string
  - name: kustomization-git-revision
    type: string
    default: master
  - name: dockerfile-path
    type: string
    description: The path to your Dockerfile
    default: "Dockerfile"
  tasks:
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    resources:
      inputs:
        - name: source
          resource: source-repo
      outputs:
        - name: image
          resource: image
    params:
    - name: TLSVERIFY
      value: "false"
    - name: DOCKERFILE
      value: "$(params.dockerfile-path)"
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: "$(params.kustomization-git-repo-url)"
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: "$(params.kustomization-git-revision)"
    runAfter:
    - build-image
  - name: apply-config
    params:
    - name: kustomization-path
      value: "$(params.kustomization-path)"
    workspaces:
    - name: source
      workspace: shared-workspace
    taskSpec:
      params:
      - name: kustomization-path
        default: "kustomization"
      workspaces:
      - name: source
      steps:
      - name: apply-kustomization
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ['/bin/bash', '-c']
        args:
        - |-
          echo "Applying kustomization in DIR \"$(params.kustomization-path)\""
          oc apply -k $(params.kustomization-path)
    runAfter:
    - fetch-repository
