apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-build-and-deploy-pacman-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: build-and-deploy-pacman
  resources:
  - name: source-repo
    resourceRef:
      name: pacman-git
  - name: image
    resourceRef:
      name: pacman-image
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: shared-workspace
      # 0.12 and later
      # volumeClaimTemplate:
      #   apiVersion: v1
      #   kind: PersistentVolumeClaim
      #   metadata:
      #     name: shared-workspace-
      #   spec:
      #     accessModes:
      #     - ReadWriteOnce
      #     resources:
      #       requests:
      #         storage: 1Gi
  params:
  - name: dockerfile-path
    value: "pacman-nodejs-app/docker/Dockerfile"
  - name: kustomization-path
    value: "kustomization"
  - name: kustomization-git-repo-url
    value: "https://github.com/mdelder/openshift-pipeline-example-pacman.git"
  - name: kustomization-git-revision
    value: "master"
