---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pacman-app-latest
  namespace: pacman-app
  annotations:
    apps.open-cluster-management.io/github-path: kustomization
spec:
  type: GitHub
  pathname: https://github.com/mdelder/openshift-pipeline-example-pacman.git
  # secretRef:
  #   name: github-credentials
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman-app
  namespace: pacman-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - pacman-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-path: kustomization
  name: pacman-app
  namespace: pacman-app
  labels:
    app: pacman-app
spec:
  channel: pacman-app/pacman-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-dev-clusters
  packageOverrides:
  - packageName: kustomization
    # packageOverrides:
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-dev-clusters
  namespace: pacman-app
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    clusterReplicas: 2
    matchExpressions:
    - key: zone
      operator: In
      values:
      - us-east
      - us-west
      - europe-west3
    matchLabels:
      environment: dev
      apps/pacman: deployed
